title: Healing For You
description:
keywords:

timezone: Australia/Sydney
google_analytics:

baseurl: /

sass:
  sass_dir: /assets/sass
  style: :compressed

repository:

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle

defaults:
  - scope:
      path: '' # an empty string here means all files in the project
    values:
      layout: 'default'
